{% set name = "bor" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bor-{{ version }}.tar.gz
  sha256: 944c058bd3304d34c47f52089fc62b9e8746d3420f3bea3a6dc020dcf351a8c1

build:
  number: 1
  noarch: python
  entry_points:
    - bor = bor.bor:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - bor
  commands:
    - pip check
    - bor --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/furkanonder/bor/
  summary: User-friendly, tiny source code searcher written by pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
